# Generated by Django 3.2.2 on 2022-10-16 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_id', models.IntegerField(verbose_name='id')),
                ('usr_login', models.CharField(max_length=150, verbose_name='login')),
                ('usr_psw', models.CharField(max_length=150, verbose_name='password')),
                ('usr_acs_lvl', models.IntegerField(verbose_name='acs_lvl')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Capital',
        ),
    ]
