# Generated by Django 3.2.2 on 2022-10-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20221016_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='author',
        ),
    ]
